version: '3'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: nocobase
      POSTGRES_PASSWORD: nocobase
      POSTGRES_DB: nocobase
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nocobase:
    image: nocobase/nocobase:latest
    restart: always
    depends_on:
      - db
    environment:
      - DB_DIALECT=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=nocobase
      - DB_USERNAME=nocobase
      - DB_PASSWORD=nocobase
    ports:
      - "8080:80"

  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password

  frontend:
    build: ./apps/frontend
    restart: always
    environment:
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
    ports:
      - "3000:3000"
    depends_on:
      - nocobase

volumes:
  pgdata:
